name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
 
trigger: none
 
pr: none
 
stages :        
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
              - checkout: self
 
              - task: AzureResourceManagerTemplateDeployment@1
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Infy-SPN'
                  subscriptionId: 'Your-Subscription-ID'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'InfyAssignment-RG'
                  location: 'eastus2'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.DefaultWorkingDirectory)/template/Vnet.json'
                  csmParametersFile: '$(System.DefaultWorkingDirectory)/template/vnet.parameters.json'
                  deploymentMode: 'Incremental'